### PR TITLE
Improve/add documentation for STM32F429I firmware management

### PR DESCRIPTION
**Pull request by edleno2**
Based on first time getting started with the STM32F429I this documentation is to help people getting started with that device, along with some additional generic getting started help.

## Description

- New:
    - STM32CubeProgrammer Utility to flash firmware guide
    - Trouble shooting guide for getting started (common getting started problems)
    - How version and checksum are managed between C# components and C++ assemblies (common getting started problem)
    - Images of Device Explorer, STM32CubeProgrammer, nanoff, etc to go with the guides
- Updated:
    - Getting started guide
    - ST-Link guide
    - Index.md's for new content
    - order files for new content

## Motivation and Context

- Resolves nanoFramework/Home#754

## Types of changes

- [x] Improvement (correction, content improvement, typoe fix, formating)
- [x] New Article (new document for docs website)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [x] My doc follows the code style of this project.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by josesimoes** [comment]
@edleno2 there are now conflicts in a couple of files. There was a PR waiting for review that had updated instructions with the new STM programmer CLI...

**Comment by josesimoes** [comment]
Considering that STLink has been marked as deprecated, it's better to just replace the STLink instructions with the new STM programmer. Please review & merge what is there now, so we can agree on how it will look like in the end.

**Comment by edleno2** [comment]
@josesimoes  - Merged my changes with yours - copied your structure and removed the duplicate images I had made.  Added my new content to the TOC.  This should be ready to merge once the checks complete.

**Review by josesimoes — APPROVED** [review]
Awesome! Thanks 👍🙂

**Pull request merged**
