### PR TITLE
General update on docfx

### PR DESCRIPTION
**Pull request by Arhell**
## Description
- General update on docfx.

## Types of changes

- [ ] Improvement (correction, content improvement, typo fix, formatting)
- [ ] New Article (new document for docs website)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [ ] My doc follows the code style of this project.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by josesimoes** [comment]
@Arhell please add back the project logo on the template (templates/nano1/logo.svg) and fav icon.

**Comment by Arhell** [comment]
> @Arhell please add back the project logo on the template (templates/nano1/logo.svg) and fav icon.

Done thanks

**Review by Arhell — COMMENTED** [review]
@josesimoes take a look please

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by Ellerbach** [comment]
Thanks @Arhell will that change the current look & feel of the site?

**Comment by Ellerbach** [comment]
@Arhell your merge is failing with an error in building with the template.
See: 
image

Detailed log here: https://dev.azure.com/nanoframework/b2e5e712-fcbe-4ea8-bd74-5c787144aece/_apis/build/builds/41057/logs/29

Full pipeline here: https://dev.azure.com/nanoframework/nanoframework%20docs/_build/results?buildId=41057&view=results

Can you please fix what's missing in the template/elsewhere?

**Comment by Ellerbach** [comment]
@Arhell for test, you have to:

Create a toc.yml file in a new devicesdetails folder. Don't both with that one, just put this inside (it's built automatically with all the device):

image

image
```yml
items:
- name: Home
  href: ../index.md
```

Make sure you hav e the latest version of docfx installed (choco install will do it)

Then run `docfx build docfx.json --serve`

It should just work fine. It was working fine before your changes. Now it throws about a 100 of errors:

image
image

**Pull request merged**
