### PR TITLE
Update contributing folder urls to https

### PR DESCRIPTION
**Pull request by Arhell**
## Types of changes

- [ ] Improvement (correction, content improvement, typo fix, formatting)
- [ ] New Article (new document for docs website)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [ ] My doc follows the code style of this project.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.

***BUILD_ALL***

### CODE REVIEW

**Comment by josesimoes** [comment]
@Arhell if this is not addressing an open issue (which seems to be the case) you just need to remove the
 `- Fixes/Closes/Resolves nanoFramework/Home#NNNN` above so that nfbot doesn't complain about it.

**Comment by josesimoes** [comment]
@Arhell in case you're not finding the build failure report here it is:
https://dev.azure.com/nanoframework/nanoframework%20docs/_build/results?buildId=44207&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=04da9304-4993-52d9-c871-c21bca046544

Nothing related with the changes you're making.
BTW, thanks for addressing these! 👍🏻

**Comment by Arhell** [comment]
> @Arhell in case you're not finding the build failure report here it is: https://dev.azure.com/nanoframework/nanoframework%20docs/_build/results?buildId=44207&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=04da9304-4993-52d9-c871-c21bca046544
> 
> Nothing related with the changes you're making. BTW, thanks for addressing these! 👍🏻

Thanks again, yes I know where to look (I remember). And yes, unfortunately my updates do not affect these errors

**Comment by Ellerbach** [comment]
> And yes, unfortunately my updates do not affect these errors

No worry, I can handle that later today and push it here. The DocLinkChecker has been improved to find even more cases, that's the result of it :-) And indeed, it's not on your changes.

**Review by Ellerbach — APPROVED** [review]
Thanks for those fixes :-)

**Pull request merged**
